const form=document.querySelector('#searchForm'),input=document.querySelector('#searchInput'),section=document.querySelector('#recentSection'),list=document.querySelector('#recentList'),key='buscamas-recent-searches';
const addressForm=document.querySelector('#addressForm'),addressInput=document.querySelector('#addressInput'),homePage=document.querySelector('#homePage'),tabsList=document.querySelector('#tabsList'),browserViews=document.querySelector('#browserViews'),appFooter=document.querySelector('#appFooter'),utilityPanel=document.querySelector('#utilityPanel'),panelTitle=document.querySelector('#panelTitle'),panelContent=document.querySelector('#panelContent'),loadingBar=document.querySelector('#loadingBar'),errorView=document.querySelector('#errorView'),errorMessage=document.querySelector('#errorMessage'),toast=document.querySelector('#toast'),linkStatus=document.querySelector('#linkStatus'),updateBanner=document.querySelector('#updateBanner'),updateText=document.querySelector('#updateText');
let tabs=[],activeTabId=null,nextTabId=1;
function sizeViews(){const height=Math.max(300,window.innerHeight-140);browserViews.style.height=height+'px';browserViews.style.width=window.innerWidth+'px';tabs.forEach(t=>{t.view.style.width=window.innerWidth+'px';t.view.style.height=height+'px'})}
const get=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
const getHistory=()=>{try{return JSON.parse(localStorage.getItem('buscamas-history')||'[]')}catch{return[]}};
const getFavorites=()=>{try{return JSON.parse(localStorage.getItem('buscamas-favorites')||'[]')}catch{return[]}};
function esc(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const items=get();section.hidden=!items.length;list.innerHTML=items.map(x=>`<button class="recent-item" data-query="${esc(x)}"><span>⌕&nbsp; ${esc(x)}</span><span>Buscar de nuevo ↗</span></button>`).join('');list.querySelectorAll('.recent-item').forEach(b=>b.onclick=()=>search(b.dataset.query))}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function updateSecurity(url){document.querySelector('#securityIcon').textContent=url.startsWith('https://')?'🔒':'⌁';document.querySelector('#securityIcon').classList.toggle('secure',url.startsWith('https://'))}
function addHistory(url){if(!/^https?:/i.test(url))return;const next=[{url,title:tabTitle(url),time:new Date().toLocaleString('es-ES')},...getHistory().filter(x=>x.url!==url)].slice(0,50);localStorage.setItem('buscamas-history',JSON.stringify(next))}
function showPanel(type){panelTitle.textContent=type==='history'?'Historial':'Favoritos';const items=type==='history'?getHistory():getFavorites();const add=type==='favorites'?'<button id="addFavorite" class="add-favorite">☆ Guardar página actual</button>':'';panelContent.innerHTML=add+(items.length?items.map((x,i)=>`<button class="panel-item" data-url="${esc(x.url)}"><span class="panel-favicon">${type==='history'?'◷':'★'}</span><span class="panel-label"><b>${esc(x.title||x.url)}</b><small>${esc(x.url)}</small></span>${type==='history'?`<small>${esc(x.time||'')}</small>`:`<span class="remove-favorite" data-remove="${i}">×</span>`}</button>`).join(''):'<div class="panel-empty">Todavía no hay elementos aquí.</div>');utilityPanel.hidden=false;document.querySelector('#addFavorite')?.addEventListener('click',()=>{const tab=active();if(!tab?.url)return;const fav=[{url:tab.url,title:tab.title},...getFavorites().filter(x=>x.url!==tab.url)].slice(0,30);localStorage.setItem('buscamas-favorites',JSON.stringify(fav));showPanel('favorites')});panelContent.querySelectorAll('.panel-item').forEach(item=>item.onclick=e=>{if(e.target.dataset.remove!==undefined){const fav=getFavorites();fav.splice(Number(e.target.dataset.remove),1);localStorage.setItem('buscamas-favorites',JSON.stringify(fav));showPanel('favorites');return}openPage(item.dataset.url);utilityPanel.hidden=true})}
function tabTitle(url){try{return new URL(url).hostname.replace('www.','')}catch{return 'Nueva pestaña'}}
function renderTabs(){tabsList.innerHTML=tabs.map(tab=>`<button class="tab ${tab.id===activeTabId?'active':''}" data-tab="${tab.id}"><span class="tab-icon">${tab.title.charAt(0).toUpperCase()}</span><span class="tab-title">${esc(tab.title)}</span><span class="tab-close" data-close="${tab.id}">×</span></button>`).join('');tabsList.querySelectorAll('.tab').forEach(el=>el.onclick=e=>{if(e.target.dataset.close)closeTab(Number(e.target.dataset.close));else activateTab(Number(el.dataset.tab))})}
function createTab(url=null){const id=nextTabId++,view=document.createElement('webview');view.className='browser-view';view.setAttribute('partition','persist:buscamas');view.setAttribute('allowpopups','');view.setAttribute('preload',new URL('./webview-preload.js',window.location.href).toString());view.dataset.tabId=id;browserViews.appendChild(view);const tab={id,view,title:'Nueva pestaña',url:''};tabs.push(tab);activateTab(id);if(url)openPage(url,id);return tab}
function activateTab(id){const tab=tabs.find(t=>t.id===id);if(!tab)return;activeTabId=id;homePage.hidden=Boolean(tab.url);tabs.forEach(t=>t.view.classList.toggle('active-view',t.id===id));addressInput.value=tab.url||'';sizeViews();renderTabs()}
function closeTab(id){const index=tabs.findIndex(t=>t.id===id);if(index<0)return;const tab=tabs[index];tab.view.remove();tabs.splice(index,1);if(!tabs.length){homePage.hidden=false;browserViews.hidden=true;appFooter.hidden=false;addressInput.value='';createTab();return}if(activeTabId===id)activateTab(tabs[Math.max(0,index-1)].id);else renderTabs()}
function active(){return tabs.find(t=>t.id===activeTabId)}
function openPage(url,id=activeTabId){try{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))return;let tab=tabs.find(t=>t.id===id);if(!tab)tab=createTab();tab.url=parsed.toString();tab.title=tabTitle(tab.url);homePage.hidden=true;browserViews.hidden=false;errorView.hidden=true;appFooter.hidden=true;loadingBar.classList.add('loading');tab.view.src=tab.url;activateTab(tab.id)}catch{notify('Dirección no válida')}}
function navigateText(raw){let value=raw.trim();if(!value)return;if(!/^https?:\/\//i.test(value)){if(value.includes('.')&&!value.includes(' '))value='https://'+value;else value='https://buscamas.es/web?q='+encodeURIComponent(value)}openPage(value)}
function search(raw){const q=raw.trim();if(!q){input.focus();input.select();return}localStorage.setItem(key,JSON.stringify([q,...get().filter(x=>x.toLowerCase()!=q.toLowerCase())].slice(0,6)));render();openPage('https://buscamas.es/web?q='+encodeURIComponent(q))}
function currentView(){return active()?.view}
form.addEventListener('click',event=>{if(event.target!==input&&event.target.tagName!=='BUTTON')input.focus()});form.onsubmit=e=>{e.preventDefault();search(input.value)};addressForm.onsubmit=e=>{e.preventDefault();navigateText(addressInput.value)};
document.querySelector('#newTabBtn').onclick=()=>createTab();document.querySelector('#backBtn').onclick=()=>{const v=currentView();if(v?.canGoBack())v.goBack()};document.querySelector('#forwardBtn').onclick=()=>{const v=currentView();if(v?.canGoForward())v.goForward()};document.querySelector('#reloadBtn').onclick=()=>currentView()?.reload();
function bindView(view,tab){view.addEventListener('ipc-message',e=>{if(e.channel==='link-hover'){linkStatus.textContent=e.args[0]||'';linkStatus.classList.add('visible')}if(e.channel==='link-leave'){linkStatus.classList.remove('visible')}});view.addEventListener('dom-ready',()=>{view.setZoomFactor(1.2);loadingBar.classList.remove('loading');errorView.hidden=true});view.addEventListener('did-start-loading',()=>{loadingBar.classList.add('loading');errorView.hidden=true});view.addEventListener('did-stop-loading',()=>loadingBar.classList.remove('loading'));view.addEventListener('did-fail-load',e=>{loadingBar.classList.remove('loading');if(e.isMainFrame&&e.errorCode<0&&e.errorCode!==-3)notify('No se pudo cargar la página; puedes reintentar desde ↻')});view.addEventListener('did-navigate',e=>{errorView.hidden=true;tab.url=e.url;tab.title=tabTitle(e.url);addHistory(e.url);updateSecurity(e.url);if(activeTabId===tab.id){addressInput.value=e.url;homePage.hidden=true}renderTabs()});view.addEventListener('did-navigate-in-page',e=>{errorView.hidden=true;tab.url=e.url;addHistory(e.url);if(activeTabId===tab.id){addressInput.value=e.url;updateSecurity(e.url)}});view.addEventListener('page-title-updated',e=>{if(e.title){tab.title=e.title.slice(0,24);renderTabs()}})}
const originalCreate=createTab;createTab=function(url=null){const tab=originalCreate(url);bindView(tab.view,tab);sizeViews();return tab};
document.querySelectorAll('.quick-card').forEach(c=>c.onclick=()=>openPage(c.dataset.url));document.querySelector('#clearRecent').onclick=()=>{localStorage.removeItem(key);render()};document.querySelector('#customizeBtn').onclick=()=>notify('Personalización disponible próximamente');document.querySelector('#historyBtn').onclick=()=>showPanel('history');document.querySelector('#favoritesBtn').onclick=()=>showPanel('favorites');document.querySelector('#addressFavorite').onclick=()=>{const tab=active();if(tab?.url){const fav=[{url:tab.url,title:tab.title},...getFavorites().filter(x=>x.url!==tab.url)];localStorage.setItem('buscamas-favorites',JSON.stringify(fav.slice(0,30)));notify('Página guardada en favoritos')}};document.querySelector('#profileBtn')?.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('buscamas-dark',document.body.classList.contains('dark'))});document.querySelector('#closePanel').onclick=()=>utilityPanel.hidden=true;document.querySelector('#retryBtn').onclick=()=>{errorView.hidden=true;const tab=active();if(tab)openPage(tab.url,tab.id)};document.querySelector('#privacyLink').onclick=e=>{e.preventDefault();notify('Tus datos se guardan localmente en este dispositivo')};document.querySelector('#aboutLink').onclick=e=>{e.preventDefault();notify('Buscamas para Windows · Versión 0.3')};
document.addEventListener('keydown',e=>{if(e.key==='Escape')utilityPanel.hidden=true});document.querySelector('#restartUpdate').onclick=()=>window.buscamas.restartAndUpdate();document.querySelector('#dismissUpdate').onclick=()=>updateBanner.hidden=true;window.buscamas.onUpdateStatus(status=>{if(status.state==='downloading')notify(`Descargando actualización… ${status.percent}%`);if(status.state==='ready'){updateText.textContent=`Buscamas ${status.version} está lista. Reinicia para aplicar la actualización.`;updateBanner.hidden=false}});
window.addEventListener('resize',sizeViews);if(localStorage.getItem('buscamas-dark')==='true')document.body.classList.add('dark');createTab();render();sizeViews();
